// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRzdpXUR91HdOwr5OdZFjIZ8QD6LTEGUQ',
    appId: '1:421155499766:web:baf92ebb816498c2ad06d7',
    messagingSenderId: '421155499766',
    projectId: 'finance-app-b875c',
    authDomain: 'finance-app-b875c.firebaseapp.com',
    storageBucket: 'finance-app-b875c.firebasestorage.app',
    measurementId: 'G-11M1F1W4PJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ0n2160MqgHHaUnz1AfaF4-j8IvAqU6E',
    appId: '1:421155499766:android:22114548db4224ddad06d7',
    messagingSenderId: '421155499766',
    projectId: 'finance-app-b875c',
    storageBucket: 'finance-app-b875c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFWqPkEbnDGp7aWdJulzfaYGLBZoCADw8',
    appId: '1:421155499766:ios:41211e02843e4891ad06d7',
    messagingSenderId: '421155499766',
    projectId: 'finance-app-b875c',
    storageBucket: 'finance-app-b875c.firebasestorage.app',
    iosBundleId: 'com.syahrul.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFWqPkEbnDGp7aWdJulzfaYGLBZoCADw8',
    appId: '1:421155499766:ios:41211e02843e4891ad06d7',
    messagingSenderId: '421155499766',
    projectId: 'finance-app-b875c',
    storageBucket: 'finance-app-b875c.firebasestorage.app',
    iosBundleId: 'com.syahrul.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRzdpXUR91HdOwr5OdZFjIZ8QD6LTEGUQ',
    appId: '1:421155499766:web:05fa07bf0c743a24ad06d7',
    messagingSenderId: '421155499766',
    projectId: 'finance-app-b875c',
    authDomain: 'finance-app-b875c.firebaseapp.com',
    storageBucket: 'finance-app-b875c.firebasestorage.app',
    measurementId: 'G-T71L59PG0Z',
  );
}
